### ISSUE TITLE
해야할 일

### ISSUE THREAD

**Issue by dakyungoh** [dakyungoh/git-hub-study#1]
- 1 단계: 브랜치 만들고 PR 리뷰를 통해 Merge하기
- [x] [Remote] 이 레포지토리 콜라보레이터에 @chanhee-park 추가하기 
- [x] [Local] main branch에서 develop branch 만들기 
- [x] [Local] develop branch에 kongdol.txt 라는 빈 텍스트 파일 만들어서 추가하기 
- [x] [Remote] develop branch의 변경사항을 github 레포지토리에 올리기 (add, commit push!) 
- [x] [Remote] develop -> main 의 Pull Requests 만들기. [@chanhee-park](https://github.com/chanhee-park) 을 리뷰어로 설정 
- [x] [Remote] 리뷰 확인 받으면 (develop -> main) merge 하기 
- [x] [Local] 리모트에서 발생한 main 변경 사항을 로컬로 pull 받아오기 

- 2 단계: 여러 feature에서 발생한 변경사항을 develop에 합치기
- [x] [Local] develop branch에서 feature/name branch 만들기 
- [x] [Local] develop branch에서 feature/skill branch 만들기 
- [x] [Local] feature/name branch 에서 kongdol.txt에 이름 추가하기(eg. 이름: 콩돌맨) 
- [x] [Local] feature/skill branch 에서 kongdol.txt에 능력 추가하기(eg. 능력: 콩돌파워) 
- [x] [Remote] feature/name-> develop 의 PR 작성 (리뷰어 [@chanhee-park] 
- [x] [Remote] feature/skill-> develop 의 PR 작성 (리뷰어 [@chanhee-park]
- [x] [Remote] feature/name-> develop PR 리뷰 받고 PR Merge 
- [x] [Remote] feature/skill-> develop 의 Merge Conflict 해소 
- [x] [Remote] feature/skill-> develop PR 리뷰 받고 PR Merge 
- [x] [Local] 리모트에서 발생한 develop 변경 사항을 로컬로 pull 받아오기 

 3단계: 기타 짜잘쓰
- [x] [Remote] develop branch를 기본 브랜치로 설정https://hbase.tistory.com/216 
- [x]  Git Branch 관리 전략 중 하나인 GitFlow 알아보기 https://ux.stories.pe.kr/183

**Comment by chanhee-park** [comment]
추억의 깃헙 이슈. close 하겠습니다.

**Comment by dakyungoh** [comment]
네~아주 오래됐군요
